version: "3.7"

services:    
    ea-chatapp:
        image: frost2203/ea-chatapp
        working_dir: /chatserver
        command: ["npm", "run", "server"]
        ports: 
            - 3000:3000
        environment: 
            MYSQL_HOST: database-1.cifxv6cgbxnq.ap-southeast-1.rds.amazonaws.com
            MYSQL_USER: admin
            MYSQL_PASSWORD: hieu2203
            MYSQL_DB: easyaccomod
        volumes: 
            - message-images:/chatserver/messageImages
        networks: 
            - ea-network
        build: ChatServer
            
    ea-backend:
        image: frost2203/ea-backend
        working_dir: /nodejsserver
        command: ["npm", "run", "server"]
        ports: 
            - 8081:8081
        environment: 
            MYSQL_HOST: database-1.cifxv6cgbxnq.ap-southeast-1.rds.amazonaws.com
            MYSQL_USER: admin
            MYSQL_PASSWORD: hieu2203
            MYSQL_DB: easyaccomod
        volumes: 
            - backend-room-images:/nodejsserver/roomImages
        networks: 
            - ea-network
        build: NodeJsServer
        
volumes:
    message-images:
    backend-room-images:

x-aws-cloudformation:
    Resources:
        EachatappTCP3000TargetGroup:
            Properties:
                HealthCheckPath: /
                HealthCheckIntervalSeconds: 10
                HealthyThresholdCount: 2
                UnhealthyThresholdCount: 2
                HealthCheckPort: 3000
                HealthCheckProtocol: HTTP
               
        
        EabackendTCP8081TargetGroup:
            Properties:
                HealthCheckPath: /
                HealthCheckIntervalSeconds: 10
                HealthyThresholdCount: 2
                UnhealthyThresholdCount: 2
                HealthCheckPort: 8081
                HealthCheckProtocol: HTTP
            
networks: 
    ea-network:
        