apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: backend-room-images
  name: backend-room-images
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
