apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\dthie\kompose\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ea-chatapp
  name: ea-chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ea-chatapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\dthie\kompose\kompose.exe -f docker-compose.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/ea-network: "true"
        io.kompose.service: ea-chatapp
    spec:
      containers:
      - args:
        - npm
        - run
        - server
        env:
        - name: MYSQL_DB_FILE
          value: /run/secrets/db-database
        - name: MYSQL_HOST_FILE
          value: /run/secrets/db-endpoint
        - name: MYSQL_PASSWORD_FILE
          value: /run/secrets/db-password
        - name: MYSQL_USER
          value: admin
        image: frost2203/ea-chatapp:aws
        imagePullPolicy: ""
        name: ea-chatapp
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /run/secrets/db-password
          name: db-password
        - mountPath: /run/secrets/db-endpoint
          name: db-endpoint
        - mountPath: /run/secrets/db-database
          name: db-database
        - mountPath: /chatserver/messageImages
          name: message-images
        workingDir: /chatserver
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: db-password
        secret:
          items:
          - key: db-password
            path: db-password
          secretName: db-password
      - name: db-endpoint
        secret:
          items:
          - key: db-endpoint
            path: db-endpoint
          secretName: db-endpoint
      - name: db-database
        secret:
          items:
          - key: db-database
            path: db-database
          secretName: db-database
status: {}
