apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ea
    http:
      paths:
      - pathType: Prefix
        path: "/api/chat"
        backend:
          service:
            name: ea-chatapp
            port: 
              number: 3000
      - pathType: Prefix
        path: "/api/backend"
        backend:
          service:
            name: ea-backend
            port:
              number: 8080
