apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: message-images
  name: message-images
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
